server:
  port: 9200
  
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/sample
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
    
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    
configuration:
  ipAddress: localhost
  environment: development
  
#prop:
#  retailers:
#  - 
#    organization: "flipkart"
#    products: "households"
#    type: "online"
#  - 
#    organization: "amazon"
#    products: "fashion"
#    type: "online"
#  - 
#    organization: "ebay"
#    products: "electronics"
#    type: "wholesale"
     