server:
  port: 9200
  
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/sample
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
    
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    
configuration:
  ipAddress: localhost
  environment: development
  
prop:
  retailer:
    - organization: filpkart 
      products: households
      type: online
    - organization: Amazon 
      products: clothes
      type: online
    - organization: ebay 
      products: mobiles
      type: online 